config/routes.rb
Rails.application.routes.draw do
  get 'search/listings'

  get 'search/events'

  get 'search/places'

  resources :package_lines

  resources :packages

  resources :socials

  resources :images

  mount RailsAdmin::Engine => '/adm', as: 'rails_admin'

    mount Sidekiq::Web => '/skiq'
    require 'sidetiq/web'

  concern :locatable do
    resources :locations
  end

  concern :reviewable do
    resources :reviews
  end

  resources :listings, concerns: [:locatable, :reviewable]

  resources :events, concerns: [:locatable, :reviewable]

  resources :clients

  resources :places, concerns: [:locatable, :reviewable]

=begin
  resources :categories do
    resources :subcategories
  end
=end

  devise_for :users, controllers: { omniauth_callbacks: 'omniauth_callbacks' }

  get 'pages/home'

  get 'pages/contact'

  get 'pages/about'

  get 'pages/package'

  get 'pages/share'

   root 'pages#home'

  match '/users/:id/finish_signup' => 'users#finish_signup', via: [:get, :patch], :as => :finish_signup

  get '/discourse/sso' => 'discourse_sso#sso'

end

app/models/listing.rb
class Listing < ActiveRecord::Base
  belongs_to :client
  has_many :subcategorizations
  has_many :subcategories, through: :subcategorizations
  has_one :payment
  has_many :reviews
  has_many :package_lines

  has_many :images, as: :imageable
  has_many :socials, as: :socialize

  scope :subcategory?, ->(subcategory){
    where(subcategories: {name: subcategory}).joins(:subcategories)
  }

  searchkick

end

app/controllers/listings_controller.rb
class ListingsController < ApplicationController
  before_action :set_listing, only: [:show, :edit, :update, :destroy]
  before_action :select_listings, only: :index

  load_and_authorize_resource

  # GET /listings
  # GET /listings.json
  def index

  end

  # GET /listings/1
  # GET /listings/1.json
  def show
  end

  # GET /listings/new
  def new
    @listing = Listing.new
  end

  # GET /listings/1/edit
  def edit
  end

  # POST /listings
  # POST /listings.json
  def create
    @listing = Listing.new(listing_params)

    respond_to do |format|
      if @listing.save
        format.html { redirect_to @listing, notice: 'Listing was successfully created.' }
        format.json { render :show, status: :created, location: @listing }
      else
        format.html { render :new }
        format.json { render json: @listing.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /listings/1
  # PATCH/PUT /listings/1.json
  def update
    respond_to do |format|
      if @listing.update(listing_params)
        format.html { redirect_to @listing, notice: 'Listing was successfully updated.' }
        format.json { render :show, status: :ok, location: @listing }
      else
        format.html { render :edit }
        format.json { render json: @listing.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /listings/1
  # DELETE /listings/1.json
  def destroy
    @listing.destroy
    respond_to do |format|
      format.html { redirect_to listings_url, notice: 'Listing was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_listing
      @listing = Listing.find(params[:id])
    end


  def select_listings
    if params[:subcat].present?
      @listings = Listing.includes(:client).subcategory?(params[:subcat])
      #@listings =
      #sc_id = Subcategory.where(name: params[:subcat])
=begin
      @listings = Listing.includes(:client).find_all do |l|
        l.subcategories(params[:subcat])
      end
=end
    #@listings = Subcategory.where(params[:subcat]).listings


    else
      @listings = Listing.includes(:client).all
    end

  end

    # Never trust parameters from the scary internet, only allow the white list through.
    def listing_params
      params.require(:listing).permit(:name, :description, :client_id, :subcategory_id, :cost, :featured, :keywords, :link, :on_package)
    end
end

app/helpers/listings_helper.rb
module ListingsHelper
end

app/views/listings/_form.html.erb
<%= form_for(@listing) do |f| %>
  <% if @listing.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@listing.errors.count, "error") %> prohibited this listing from being saved:</h2>

      <ul>
      <% @listing.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :client_id %><br>
    <%= f.text_field :client_id %>
  </div>
  <div class="field">
    <%= f.label :subcategories %><br>
    <%= f.text_field :subcategories %>
  </div>
  <div class="field">
    <%= f.label :cost %><br>
    <%= f.text_field :cost %>
  </div>
  <div class="field">
    <%= f.label :featured %><br>
    <%= f.check_box :featured %>
  </div>
  <div class="field">
    <%= f.label :keywords %><br>
    <%= f.text_area :keywords %>
  </div>
  <div class="field">
    <%= f.label :link %><br>
    <%= f.text_field :link %>
  </div>
  <div class="field">
    <%= f.label :on_package %><br>
    <%= f.check_box :on_package %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/listings/edit.html.erb
<h1>Editing listing</h1>

<%= render 'form' %>

<%= link_to 'Show', @listing %> |
<%= link_to 'Back', listings_path %>

app/views/listings/index.html.erb
<div class="container">
  <div class="row">
    <h3>Listings</h3>

  </div>
  <!--div class="row" id="ad-top" style="background-color: #333333; height: 50px">
    Ad space - Top of subcategory
  </div-->
  <div class="row">
<div class="medium-3 columns" style="padding-right: -20px;">
  <div clas="row" style="height: 250px;">
    Filters coming here.
  </div>
  <div class="row">
<div id="ad-left-callout" style="background-color: #228811;height:300px">
  Ad space - Side callout
</div>
  </div>

  </div>
<div class="columns small-9">
  <div class="row" id="ad-slider-listing">

    <div class="banner">
      <ul>
        <li style="background-color: #222; height:200px">This is a slide.</li>
        <li style="background-color: #999; height:200px">This is another slide.</li>
        <li style="background-color: #DDD; height:200px">This is a final slide.</li>
      </ul>
    </div>


  </div>
  <div class="row" id="listings-lister" style="border: 1px solid #333333">
    <div class="columns small-9">
    <ul>
      <% @listings.each do |listing| %>
          <li>
          <ul>
            <li><%= listing.name %></li>
            <li><%= listing.description %></li>
            <li><%= listing.client.name %></li>
            <li><% listing.subcategories.each do |c| %></li>
                    <li>
                      <%= c.name %>
                    </li><% end %>
            <li><%= listing.cost %></li>
            <li><%= listing.featured %></li>
            <li><%= listing.keywords %></li>
            <li><%= listing.link %></li>
            <li><%= link_to 'Show', listing %></li>
            <!--li><%= link_to 'Edit', edit_listing_path(listing) %></li>
            <li><%= link_to 'Destroy', listing, method: :delete, data: { confirm: 'Are you sure?' } %></li-->
          </ul>
          </li>
      <% end %>
    </ul>
    </div>
  </div>
  </div>
  </div>

</div>

<br>


<% #link_to 'New Listing', new_listing_path %>

app/views/listings/new.html.erb
<h1>New listing</h1>

<%= render 'form' %>

<%= link_to 'Back', listings_path %>

app/views/listings/show.html.erb
<div class="row"><div class="columns small-4">
<%= image_tag @listing.images.first %>
</div>
  <div class="columns small-8">
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @listing.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @listing.description %>
</p>

<p>
  <strong>Client:</strong>
  <%= @listing.client.name %>
</p>

<p>
  <strong>Subcategories:</strong>
  <%= @listing.subcategories.first.name %>
</p>

<p>
  <strong>Fee:</strong>
  <%= @listing.cost %>
</p>

<p>
  <strong>Featured:</strong>
  <%= @listing.featured %>
</p>

<p>
  <strong>Keywords:</strong>
  <%= @listing.keywords %>
</p>

<p>
  <strong>Link:</strong>
  <%= @listing.link %>
</p>

<p id="addToPackageButton" style="display: none;">
  <button><strong>Add this listing to my Package</strong></button>
</p>
  </div>

</div>

<div class="row">
  <div class="columns small-12">
    Reviews for this listing
    <div class="row">
      <div class="columns small-10">
        <%= @listing.reviews.first %>
      </div>
      <div class="row">
        <%= link_to "Add Review", new_listing_review_path(@listing) %>
      </div>
    </div>
  </div>
</div>

<script>
  $(document).ready(function(){
      if (typeof sessionStorage["package_amount"] !== 'undefined')
      {
          $("#addToPackageButton").show();
      }
      else
      {
          $("#addToPackageButton").hide();
      }
  });
</script>