config/routes.rb
Rails.application.routes.draw do
  get 'search/listings'

  get 'search/events'

  get 'search/places'

  resources :package_lines

  resources :packages

  resources :socials

  resources :images

  mount RailsAdmin::Engine => '/adm', as: 'rails_admin'

    mount Sidekiq::Web => '/skiq'
    require 'sidetiq/web'

  concern :locatable do
    resources :locations
  end

  concern :reviewable do
    resources :reviews
  end

  resources :listings, concerns: [:locatable, :reviewable]

  resources :events, concerns: [:locatable, :reviewable]

  resources :clients

  resources :places, concerns: [:locatable, :reviewable]

=begin
  resources :categories do
    resources :subcategories
  end
=end

  devise_for :users, controllers: { omniauth_callbacks: 'omniauth_callbacks' }

  get 'pages/home'

  get 'pages/contact'

  get 'pages/about'

  get 'pages/package'

  get 'pages/share'

   root 'pages#home'

  match '/users/:id/finish_signup' => 'users#finish_signup', via: [:get, :patch], :as => :finish_signup

  get '/discourse/sso' => 'discourse_sso#sso'

end

app/models/subcategory.rb
class Subcategory < ActiveRecord::Base
  belongs_to :category
  has_many :subcategorizations
  has_many :ads
  has_many :listings, through: :subcategorizations
  has_many :places, through: :subcategorizations
  has_many :events, through: :subcategorizations
end

app/controllers/subcategories_controller.rb
class SubcategoriesController < ApplicationController
  before_action :set_subcategory, only: [:show, :edit, :update, :destroy]

  load_and_authorize_resource

  # GET /subcategories
  # GET /subcategories.json
  def index
    @subcategories = Subcategory.all
  end

  # GET /subcategories/1
  # GET /subcategories/1.json
  def show
  end

  # GET /subcategories/new
  def new
    @subcategory = Subcategory.new
  end

  # GET /subcategories/1/edit
  def edit
  end

  # POST /subcategories
  # POST /subcategories.json
  def create
    @subcategory = Subcategory.new(subcategory_params)

    respond_to do |format|
      if @subcategory.save
        format.html { redirect_to @subcategory, notice: 'Subcategory was successfully created.' }
        format.json { render :show, status: :created, location: @subcategory }
      else
        format.html { render :new }
        format.json { render json: @subcategory.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /subcategories/1
  # PATCH/PUT /subcategories/1.json
  def update
    respond_to do |format|
      if @subcategory.update(subcategory_params)
        format.html { redirect_to @subcategory, notice: 'Subcategory was successfully updated.' }
        format.json { render :show, status: :ok, location: @subcategory }
      else
        format.html { render :edit }
        format.json { render json: @subcategory.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /subcategories/1
  # DELETE /subcategories/1.json
  def destroy
    @subcategory.destroy
    respond_to do |format|
      format.html { redirect_to subcategories_url, notice: 'Subcategory was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_subcategory
      @subcategory = Subcategory.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def subcategory_params
      params.require(:subcategory).permit(:name, :category_id_id, :image)
    end
end

app/helpers/subcategories_helper.rb
module SubcategoriesHelper
end

app/views/subcategories/_form.html.erb
<%= form_for(@subcategory) do |f| %>
  <% if @subcategory.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@subcategory.errors.count, "error") %> prohibited this subcategory from being saved:</h2>

      <ul>
      <% @subcategory.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :category_id_id %><br>
    <%= f.text_field :category_id_id %>
  </div>
  <div class="field">
    <%= f.label :image %><br>
    <%= f.text_field :image %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/subcategories/edit.html.erb
<h1>Editing subcategory</h1>

<%= render 'form' %>

<%= link_to 'Show', @subcategory %> |
<%= link_to 'Back', category_subcategories_path %>

app/views/subcategories/index.html.erb
<h1>Listing subcategories</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Category</th>
      <th>Image</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @subcategories.each do |subcategory| %>
      <tr>
        <td><%= subcategory.name %></td>
        <td><%= subcategory.category_id %></td>
        <td><%= subcategory.image %></td>
        <td><%= link_to 'Show', subcategory %></td>
        <td><%= link_to 'Edit', edit_category_subcategory_path(subcategory) %></td>
        <td><%= link_to 'Destroy', subcategory, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Subcategory', new_category_subcategory_path %>

app/views/subcategories/new.html.erb
<h1>New subcategory</h1>

<%= render 'form' %>

<%= link_to 'Back', category_subcategories_path %>

app/views/subcategories/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @subcategory.name %>
</p>

<p>
  <strong>Category:</strong>
  <%= @subcategory.category_id %>
</p>

<p>
  <strong>Image:</strong>
  <%= @subcategory.image %>
</p>

<%= link_to 'Edit', edit_category_subcategory_path(@subcategory) %> |
<%= link_to 'Back', category_subcategories_path %>