config/routes.rb
Rails.application.routes.draw do
  get 'search/listings'

  get 'search/events'

  get 'search/places'

  resources :package_lines

  resources :packages

  resources :socials

  resources :images

  mount RailsAdmin::Engine => '/adm', as: 'rails_admin'

    mount Sidekiq::Web => '/skiq'
    require 'sidetiq/web'

  concern :locatable do
    resources :locations
  end

  concern :reviewable do
    resources :reviews
  end

  resources :listings, concerns: [:locatable, :reviewable]

  resources :events, concerns: [:locatable, :reviewable]

  resources :clients

  resources :places, concerns: [:locatable, :reviewable]

=begin
  resources :categories do
    resources :subcategories
  end
=end

  devise_for :users, controllers: { omniauth_callbacks: 'omniauth_callbacks' }

  get 'pages/home'

  get 'pages/contact'

  get 'pages/about'

  get 'pages/package'

  get 'pages/share'

   root 'pages#home'

  match '/users/:id/finish_signup' => 'users#finish_signup', via: [:get, :patch], :as => :finish_signup

  get '/discourse/sso' => 'discourse_sso#sso'

end

app/models/place.rb
class Place < ActiveRecord::Base
  has_many :subcategorizations
  has_many :subcategories, through: :subcategorizations
  has_many :reviews

  has_many :images, as: :imageable

  searchkick
end

app/controllers/places_controller.rb
class PlacesController < ApplicationController
  before_action :set_place, only: [:show, :edit, :update, :destroy]
  layout "show-place-layout", only: :show

  load_and_authorize_resource
  
  # GET /places
  # GET /places.json
  def index
    @places = Place.all
  end

  # GET /places/1
  # GET /places/1.json
  def show
    @pictures = @place.images
  end

  # GET /places/new
  def new
    @place = Place.new
  end

  # GET /places/1/edit
  def edit
  end

  # POST /places
  # POST /places.json
  def create
    @place = Place.new(place_params)

    respond_to do |format|
      if @place.save
        format.html { redirect_to @place, notice: 'Place was successfully created.' }
        format.json { render :show, status: :created, location: @place }
      else
        format.html { render :new }
        format.json { render json: @place.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /places/1
  # PATCH/PUT /places/1.json
  def update
    respond_to do |format|
      if @place.update(place_params)
        format.html { redirect_to @place, notice: 'Place was successfully updated.' }
        format.json { render :show, status: :ok, location: @place }
      else
        format.html { render :edit }
        format.json { render json: @place.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /places/1
  # DELETE /places/1.json
  def destroy
    @place.destroy
    respond_to do |format|
      format.html { redirect_to places_url, notice: 'Place was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_place
      @place = Place.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def place_params
      params.require(:place).permit(:name, :description, :details, :fees, :fees, :area, :kind, :activities, :keyword)
    end
end

app/helpers/places_helper.rb
module PlacesHelper
end

app/views/places/_form.html.erb
<%= form_for(@place) do |f| %>
  <% if @place.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@place.errors.count, "error") %> prohibited this place from being saved:</h2>

      <ul>
      <% @place.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :details %><br>
    <%= f.text_area :details %>
  </div>
  <div class="field">
    <%= f.label :fees %><br>
    <%= f.text_field :fees %>
  </div>
  <div class="field">
    <%= f.label :fees %><br>
    <%= f.text_field :fees %>
  </div>
  <div class="field">
    <%= f.label :area %><br>
    <%= f.text_field :area %>
  </div>
  <div class="field">
    <%= f.label :kind %><br>
    <%= f.text_field :kind %>
  </div>
  <div class="field">
    <%= f.label :activities %><br>
    <%= f.text_area :activities %>
  </div>
  <div class="field">
    <%= f.label :keyword %><br>
    <%= f.text_area :keyword %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/places/edit.html.erb
<h1>Editing place</h1>

<%= render 'form' %>

<%= link_to 'Show', @place %> |
<%= link_to 'Back', places_path %>

app/views/places/index.html.erb
<h1>Listing places</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th>Details</th>
      <th>Fees</th>
      <th>Fees</th>
      <th>Area</th>
      <th>Kind</th>
      <th>Activities</th>
      <th>Keyword</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @places.each do |place| %>
      <tr>
        <td><%= place.name %></td>
        <td><%= place.description %></td>
        <td><%= place.details %></td>
        <td><%= place.fees %></td>
        <td><%= place.fees %></td>
        <td><%= place.area %></td>
        <td><%= place.kind %></td>
        <td><%= place.activities %></td>
        <td><%= place.keyword %></td>
        <td><%= link_to 'Show', place %></td>
        <td><%= link_to 'Edit', edit_place_path(place) %></td>
        <td><%= link_to 'Destroy', place, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Place', new_place_path %>

app/views/places/new.html.erb
<h1>New place</h1>

<%= render 'form' %>

<%= link_to 'Back', places_path %>

app/views/places/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @place.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @place.description %>
</p>

<p>
  <strong>Details:</strong>
  <%= @place.details %>
</p>

<p>
  <strong>Fees:</strong>
  <%= @place.fees %>
</p>

<p>
  <strong>Fees:</strong>
  <%= @place.fees %>
</p>

<p>
  <strong>Area:</strong>
  <%= @place.area %>
</p>

<p>
  <strong>Kind:</strong>
  <%= @place.kind %>
</p>

<p>
  <strong>Activities:</strong>
  <%= @place.activities %>
</p>

<p>
  <strong>Keyword:</strong>
  <%= @place.keyword %>
</p>

<%= link_to 'Edit', edit_place_path(@place) %> |
<%= link_to 'Back', places_path %>